import type { Metadata } from "next";
import { FamilyGuideLayout } from "../../components/family/FamilyGuideLayout";
import { PrintableChecklist } from "../../components/family/PrintableChecklist";
import { SafetyNotice } from "../../components/family/SafetyNotice";
import { firstHoursChecklist } from "../../data/family";

export const metadata: Metadata = { title: "Someone I love was just incarcerated | Outside Inmates", description: "A practical first-hours guide for families after incarceration." };

export default function JustIncarceratedPage() {
  return <FamilyGuideLayout slug="just-incarcerated"><div className="guide-reading"><section id="locate"><h2>First, confirm where they are.</h2><p>Start with official corrections, jail, or court information for the place where the arrest or transfer happened. If information is not available yet, write down what you know and try again later rather than relying on a message from an unknown caller.</p></section><section><h2>Write down important information.</h2><p>Keep the full legal name, date of birth, case or booking information if known, facility name, official phone number, and any resident or inmate number together. Add the date and name of anyone you speak with.</p></section><section><h2>Understand the first communication delay.</h2><p>Intake, transport, safety checks, classification, and housing changes can delay communication. A delay does not always tell you what is happening. Ask the facility what communication is available and when to check again.</p></section><SafetyNotice /><section><h2>Learn the facility’s rules.</h2><p>Ask about calls, mail, approved payments, visitation, and who can receive information. Policies differ, so confirm details directly with the facility before you spend money or travel.</p></section><section><h2>Prepare for calls.</h2><p>When contact is available, keep the first conversation simple. Share urgent household information, ask what they need you to confirm, and write down any provider name or account information slowly.</p></section><section><h2>Tell children carefully.</h2><p>Choose words that fit the child’s age and what they already know. You can say that this is an adult situation, it is not their fault, and they can ask questions. Avoid promising release dates or contact you cannot confirm.</p></section><section><h2>Take care of immediate household needs.</h2><p>Make a short list: child care, medication, school, work, pets, rent, transportation, and a person you can call. You do not have to solve every later problem today.</p></section><section><h2>Know when legal help may be needed.</h2><p>If you have a specific legal deadline, a court question, or need advice about someone’s rights, seek guidance from a qualified legal professional or legal-aid organization. This guide is general information, not legal advice.</p></section></div><PrintableChecklist title="First-hours checklist" intro="Use this as a calm reminder, not a test. Check off only what helps today." items={firstHoursChecklist} /></FamilyGuideLayout>;
}
