"use client";

import { useMemo, useState } from "react";
import { JourneyRecommendation, type JourneyRecommendationData } from "./JourneyRecommendation";

type Answer = "yes" | "no" | "not-sure" | "self" | "someone" | "finding-someone" | "communication" | "housing" | "legal" | "children" | "mental-health" | "recovery" | "documents" | "employment" | "transportation" | "overwhelmed";
type Question = { id: "arrest" | "incarcerated" | "release" | "supportFor" | "urgent"; prompt: string; options: { label: string; value: Answer }[] };

const questions: Question[] = [
  { id: "arrest", prompt: "Has an arrest happened recently?", options: [{ label: "Yes", value: "yes" }, { label: "No", value: "no" }, { label: "I am not sure", value: "not-sure" }] },
  { id: "incarcerated", prompt: "Is someone currently incarcerated?", options: [{ label: "Yes", value: "yes" }, { label: "No", value: "no" }, { label: "I am not sure", value: "not-sure" }] },
  { id: "release", prompt: "Is release expected soon?", options: [{ label: "Yes", value: "yes" }, { label: "No", value: "no" }, { label: "I am not sure", value: "not-sure" }] },
  { id: "supportFor", prompt: "Are you looking for help for yourself or someone else?", options: [{ label: "For myself", value: "self" }, { label: "For someone else", value: "someone" }, { label: "I am not sure", value: "not-sure" }] },
  { id: "urgent", prompt: "What feels most urgent today?", options: [{ label: "Finding someone", value: "finding-someone" }, { label: "Communication", value: "communication" }, { label: "Housing", value: "housing" }, { label: "Legal information", value: "legal" }, { label: "Children and family", value: "children" }, { label: "Mental health", value: "mental-health" }, { label: "Recovery", value: "recovery" }, { label: "Documents", value: "documents" }, { label: "Employment", value: "employment" }, { label: "Transportation", value: "transportation" }, { label: "I am overwhelmed", value: "overwhelmed" }] },
];

function getRecommendation(answers: Partial<Record<Question["id"], Answer>>): JourneyRecommendationData {
  const urgent = answers.urgent;
  const resourceLinks = [{ label: "Browse the Resource Finder", href: "/resources" }, { label: "Explore Family Support", href: "/families" }];
  if (answers.arrest === "yes") return { title: "Start with the first-hours path.", body: "Confirm only the information you can verify, protect yourself from urgent payment scams, and take one household need at a time.", href: "/start/just-arrested", action: "Open the just-arrested path", links: [{ label: "Family Support", href: "/families" }, { label: "Legal help resources", href: "/resources/results?category=legal-help" }, ...resourceLinks] };
  if (answers.release === "yes") return { title: "Start with preparing for coming home.", body: "Begin by confirming official release details, then make a small first-week plan that can adapt if the timeline changes.", href: "/start/coming-home", action: "Open the coming-home path", links: [{ label: "Reentry planning resources", href: "/resources/results?category=reentry-planning" }, { label: "Identification and documents", href: "/resources/results?category=identification-documents" }, ...resourceLinks] };
  if (answers.incarcerated === "yes") return { title: "Start with managing incarceration from the outside.", body: "Find the current contact rules, make a plan for the household, and remember that support can include boundaries.", href: "/start/currently-incarcerated", action: "Open the currently-incarcerated path", links: [{ label: "Communication and visitation", href: "/resources/results?category=communication-visitation" }, { label: "Support for children", href: "/families/children" }, ...resourceLinks] };
  if (answers.supportFor === "self") return { title: "Start with rebuilding at your pace.", body: "Choose one basic need that would make today more stable, then use the Resource Finder to explore the next useful support.", href: "/start/rebuilding", action: "Open the rebuilding path", links: [{ label: "Housing resources", href: "/resources/results?category=housing" }, { label: "Food and basic needs", href: "/resources/results?category=food-basic-needs" }, ...resourceLinks] };
  if (answers.supportFor === "someone") return { title: "Start with practical support that respects their choices.", body: "Ask what would help most, avoid promises you cannot keep, and connect the person with services you can confirm.", href: "/start/supporting-someone", action: "Open the supporting-someone path", links: [{ label: "Family Support", href: "/families" }, { label: "Find a resource", href: "/resources" }, ...resourceLinks] };
  const urgentMap: Partial<Record<Answer, JourneyRecommendationData>> = {
    "finding-someone": { title: "Start by confirming where they are.", body: "Use official court, jail, or corrections information. Do not rely on a message from an unknown caller.", href: "/start/just-arrested", action: "Open the first-hours path", links: [{ label: "Family Support", href: "/families" }, ...resourceLinks] },
    communication: { title: "Start with communication and visitation.", body: "Confirm the facility’s current contact rules before setting up accounts or sending money.", href: "/start/currently-incarcerated", action: "Open the communication path", links: [{ label: "Communication resources", href: "/resources/results?category=communication-visitation" }, ...resourceLinks] },
    housing: { title: "Start with a safer place to land.", body: "Explore one housing option at a time and confirm details directly with any provider.", href: "/start/rebuilding", action: "Open the rebuilding path", links: [{ label: "Housing resources", href: "/resources/results?category=housing" }, ...resourceLinks] },
    legal: { title: "Start by finding the right legal questions.", body: "Outside Inmates cannot give legal advice, but you can use this starting point to find legal-aid and advocacy resources.", href: "/resources/results?category=legal-help", action: "Browse legal-help resources", links: resourceLinks },
    children: { title: "Start with support for children and caregivers.", body: "Small, honest conversations and dependable routines can be useful first steps.", href: "/families/children", action: "Open the children guide", links: [{ label: "Family Support", href: "/families" }, ...resourceLinks] },
    "mental-health": { title: "Start with emotional support.", body: "You deserve a place to talk through the pressure. If there is an emotional crisis, the 988 Lifeline offers call, text, and chat support.", href: "/families/emotional-support", action: "Open emotional support", links: [{ label: "Mental health resources", href: "/resources/results?category=mental-health" }, ...resourceLinks] },
    recovery: { title: "Start with recovery support that fits today.", body: "A first conversation can help you identify treatment, peer, or practical support without requiring you to have every answer.", href: "/resources/results?category=substance-use-recovery", action: "Browse recovery resources", links: resourceLinks },
    documents: { title: "Start with identification and documents.", body: "Gather what you already have, then ask a document-navigation provider what to prepare next.", href: "/resources/results?category=identification-documents", action: "Browse document resources", links: resourceLinks },
    employment: { title: "Start with work and training support.", body: "A résumé, credential, or job search can wait until the practical basics are steadier if that is what you need.", href: "/resources/results?category=employment", action: "Browse employment resources", links: resourceLinks },
    transportation: { title: "Start with transportation options.", body: "Focus on the next appointment, job interview, or essential trip, then check what support may be available.", href: "/resources/results?category=transportation", action: "Browse transportation resources", links: resourceLinks },
    overwhelmed: { title: "Start with one small step.", body: "You do not have to solve the whole situation today. Choose the path that feels least overwhelming, or find emotional support first.", href: "/start/not-sure", action: "Review the starting points", links: [{ label: "Emotional support", href: "/families/emotional-support" }, ...resourceLinks] },
  };
  return urgentMap[urgent ?? "not-sure"] ?? { title: "Start with the need that feels most urgent.", body: "You can browse a guided path or search the Resource Finder by category. Your answers are not saved.", href: "/start/not-sure", action: "Review the paths", links: resourceLinks };
}

export function JourneySelector() {
  const [index, setIndex] = useState(0);
  const [answers, setAnswers] = useState<Partial<Record<Question["id"], Answer>>>({});
  const current = questions[index];
  const complete = index === questions.length;
  const recommendation = useMemo(() => getRecommendation(answers), [answers]);
  function choose(value: Answer) { setAnswers((currentAnswers) => ({ ...currentAnswers, [current.id]: value })); setIndex((currentIndex) => Math.min(currentIndex + 1, questions.length)); }
  function restart() { setAnswers({}); setIndex(0); }

  return <section className="journey-selector" aria-labelledby="journey-selector-title"><div className="journey-selector-intro"><p className="eyebrow">A private, on-page guide</p><h2 id="journey-selector-title">Find a place to begin.</h2><p>Your answers stay on this page. They are not saved, sent, or used to decide what help you qualify for.</p></div><p className="sr-only" aria-live="polite">{complete ? "Your suggested starting point is ready." : `Question ${index + 1} of ${questions.length}`}</p>{complete ? <div className="journey-selector-result"><JourneyRecommendation recommendation={recommendation} /><button className="journey-selector-back" type="button" onClick={restart}>Start over</button></div> : <div className="journey-selector-question"><p className="journey-selector-progress" aria-hidden="true">Question {index + 1} of {questions.length}</p><fieldset><legend>{current.prompt}</legend><div>{current.options.map((option) => <button type="button" key={option.value} onClick={() => choose(option.value)}>{option.label}<span aria-hidden="true">→</span></button>)}</div></fieldset>{index > 0 && <button className="journey-selector-back" type="button" onClick={() => setIndex((currentIndex) => currentIndex - 1)}>Back</button>}</div>}</section>;
}
