import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "../components/layout";
import { PageHero } from "../components/page-hero";
import { plannedPublicDocuments, organizationStatusItems, readableStatusDate } from "../data/organization";

export const metadata: Metadata = {
  title: "Transparency | Outside Inmates",
  description: "Clear, current information about Outside Inmates' formation, governance, funding, and public documents.",
};

export default function TransparencyPage() {
  return <><a className="skip-link" href="#main-content">Skip to content</a><SiteHeader /><main id="main-content" className="organization-page transparency-page"><PageHero variant="page" mediaKey="transparency.hero" eyebrow="Transparency" title="Built in public, governed with care." description="Outside Inmates is committed to clear information about how the organization is built, governed, funded, and maintained." /><section className="section transparency-status-section" aria-labelledby="current-status-heading"><div className="container"><div className="organization-section-lede"><p className="eyebrow">Current status</p><h2 id="current-status-heading">What is true today.</h2><p>These entries are written to be updated as the organization develops. Each status is expressed in words, not color alone.</p></div><div className="organization-status-grid">{organizationStatusItems.map((item) => <article className="organization-status-card" key={item.label}><div className="organization-status-card-heading"><p className="eyebrow">{item.label}</p><span className={`organization-status-label status-${item.status}`}>{item.statusLabel}</span></div><p>{item.description}</p>{item.plannedDocuments ? <ul>{item.plannedDocuments.map((document) => <li key={document}>{document}</li>)}</ul> : null}<footer>Last updated <time dateTime={item.lastUpdated}>{readableStatusDate(item.lastUpdated)}</time></footer></article>)}</div></div></section><section className="organization-documents-section" aria-labelledby="planned-documents-heading"><div className="container organization-documents-layout"><div><p className="eyebrow">Documents we plan to publish</p><h2 id="planned-documents-heading">A public record as it becomes available.</h2><p>These are not links yet. Nothing is represented as filed, approved, or published before it actually is.</p></div><ul className="organization-document-list">{plannedPublicDocuments.map((document) => <li key={document.label}><div><h3>{document.label}</h3><p>{document.description}</p></div><span aria-label={`${document.label}: not yet available`}>Not yet available</span></li>)}</ul></div></section></main><SiteFooter /></>;
}
