import type { Metadata } from "next";
import { FamilyGuideLayout } from "../../components/family/FamilyGuideLayout";
import { SupportCallout } from "../../components/family/SupportCallout";

export const metadata: Metadata = { title: "Emotional Support | Outside Inmates", description: "Compassionate, practical support for the emotional impact of incarceration on families." };

export default function EmotionalSupportPage() {
  return <FamilyGuideLayout slug="emotional-support"><div className="guide-reading"><section><h2>Some losses do not have a clean name.</h2><p>You may miss someone who is still alive, feel angry at them, feel relieved about distance, or worry about what it means to say any of that out loud. Those mixed feelings can be part of trying to live through a difficult situation.</p></section><section><h2>Grief, anger, shame, and isolation.</h2><p>Incarceration can change routines, relationships, finances, and how safe it feels to talk with other people. You deserve support that does not require you to defend your feelings or minimize the impact on your life.</p></section><section><h2>Relationship boundaries and financial strain.</h2><p>Care and loyalty do not require you to say yes to every request. It can help to decide what you can offer, what you need time to consider, and what you cannot take on. A trusted professional can help if money, conflict, or safety feels overwhelming.</p></section><section><h2>Caregiver fatigue and peer support.</h2><p>Peer support can reduce isolation, but it is not a replacement for professional care. Consider a therapist, counselor, support group, health-care provider, or community professional when you want a dedicated space to talk through what is happening.</p></section><section className="urgent-help-panel"><p className="eyebrow">Urgent mental health help</p><h2>When someone needs immediate emotional support.</h2><p>If you or someone else is in emotional distress or crisis, call or text <strong>988</strong> or use the 988 Lifeline chat. If there is immediate physical danger, call emergency services. 988 is crisis support, not a general customer service line.</p><a className="button button-primary" href="https://988lifeline.org/get-help/" target="_blank" rel="noreferrer">Contact 988 Lifeline <span aria-hidden="true">↗</span></a></section></div><SupportCallout title="Getting support is not a betrayal." body="Making room for your own safety and well-being can help you make clearer choices for yourself and the people who depend on you." href="/resources/results?category=mental-health" action="Find mental health resources" /></FamilyGuideLayout>;
}
