"use client";

import type { ReentryWorksheet as ReentryWorksheetData } from "../../data/reentry";

export function ReentryWorksheet({ worksheet }: { worksheet: ReentryWorksheetData }) {
  if (worksheet.kind === "document-tracker") return <section className="reentry-worksheet" aria-labelledby="reentry-worksheet-title"><div className="reentry-worksheet-heading"><div><p className="eyebrow">Keep this private</p><h2 id="reentry-worksheet-title">{worksheet.title}</h2><p>{worksheet.intro}</p></div><button className="button button-secondary" type="button" onClick={() => window.print()}>Print worksheet</button></div><div className="reentry-table-wrap"><table><caption className="sr-only">Document tracker worksheet</caption><thead><tr><th scope="col">Document</th><th scope="col">Do I have it?</th><th scope="col">Where is it?</th><th scope="col">Who do I contact?</th><th scope="col">What do I need?</th><th scope="col">Status</th></tr></thead><tbody>{worksheet.fields.map((field) => <tr key={field}><th scope="row">{field}</th>{["Do I have it?", "Where is it?", "Who do I contact?", "What do I need?", "Status"].map((label) => <td key={label}><label className="sr-only" htmlFor={`${field}-${label}`}>{field}: {label}</label><input id={`${field}-${label}`} type="text" autoComplete="off" /></td>)}</tr>)}</tbody></table></div></section>;
  if (worksheet.kind === "transport-planner") return <section className="reentry-worksheet" aria-labelledby="reentry-worksheet-title"><div className="reentry-worksheet-heading"><div><p className="eyebrow">Keep this private</p><h2 id="reentry-worksheet-title">{worksheet.title}</h2><p>{worksheet.intro}</p></div><button className="button button-secondary" type="button" onClick={() => window.print()}>Print planner</button></div><div className="reentry-table-wrap"><table><caption className="sr-only">Weekly transportation planner</caption><thead><tr><th scope="col">Day</th><th scope="col">Essential trip or appointment</th><th scope="col">Transportation plan</th><th scope="col">Backup plan</th></tr></thead><tbody>{worksheet.fields.map((field) => <tr key={field}><th scope="row">{field}</th>{["Essential trip or appointment", "Transportation plan", "Backup plan"].map((label) => <td key={label}><label className="sr-only" htmlFor={`${field}-${label}`}>{field}: {label}</label><input id={`${field}-${label}`} type="text" autoComplete="off" /></td>)}</tr>)}</tbody></table></div></section>;
  return <section className="reentry-worksheet" aria-labelledby="reentry-worksheet-title"><div className="reentry-worksheet-heading"><div><p className="eyebrow">Keep this private</p><h2 id="reentry-worksheet-title">{worksheet.title}</h2><p>{worksheet.intro}</p></div><button className="button button-secondary" type="button" onClick={() => window.print()}>Print worksheet</button></div><div className="reentry-worksheet-fields">{worksheet.fields.map((field) => <label key={field}>{field}<input type="text" autoComplete="off" /></label>)}</div></section>;
}
