import type { Metadata } from "next";
import { FamilyGuideLayout } from "../../components/family/FamilyGuideLayout";
import { PrintableChecklist } from "../../components/family/PrintableChecklist";
import { visitPreparationChecklist } from "../../data/family";

export const metadata: Metadata = { title: "Visitation Guide | Outside Inmates", description: "A practical, general visit preparation guide for families." };

export default function VisitationPage() {
  return <FamilyGuideLayout slug="visitation"><div className="guide-reading"><section><h2>Find the official rules first.</h2><p>Use the facility’s own visitor information to confirm everything before you travel. Ask about approval, background checks, identification, scheduling, arrival times, children, clothing, property, and accessibility.</p></section><section><h2>Approval and identification.</h2><p>Some facilities require visitors to be approved ahead of time and may have separate requirements for children or caregivers. Confirm what identification is required, whether copies are accepted, and whether a name change or other detail needs documentation.</p></section><section><h2>Prepare for arrival and check-in.</h2><p>Plan for traffic, parking, lines, security screening, and the possibility that a visit may change. Bring only what the facility explicitly allows. Ask in advance about medication, infant supplies, mobility devices, or other accessibility needs.</p></section><section><h2>Prepare children and plan transportation.</h2><p>Tell children what check-in may feel like in plain language and give them a way to signal they need a break. Confirm transportation, return plans, food, child care, and enough time for travel before the day arrives.</p></section><section><h2>Make space for after the visit.</h2><p>People can feel relieved, sad, angry, disconnected, or calm after a visit. If possible, leave room for rest, food, a familiar routine, or a conversation later rather than demanding a reaction right away.</p></section></div><PrintableChecklist title="Visit preparation checklist" intro="Facility rules vary. Use this checklist alongside the official instructions for the specific place you are visiting." items={visitPreparationChecklist} /></FamilyGuideLayout>;
}
